### ISSUE TITLE
更新不了数据

### ISSUE THREAD

**Issue by yaleidev** [Haley-Wong/JKDBModel#12]
解决了

**Comment by Joker-King** [comment]
不好意思，才看到，解决了么？


发自 网易邮箱大师
在2015年12月14日 17:29，JiangYaLei 写道:

(BOOL)update
{
JKDBHelper *jkDB = [JKDBHelper shareInstance];
__block BOOL res = NO;
[jkDBdbQueue inDatabase:^(FMDatabase *db) {
NSString *tableName = NSStringFromClass(selfclass);
id primaryValue = [self valueForKey:primaryId];
if (!primaryValue || primaryValue <= 0) {
return ;
}
NSMutableString *keyString = [NSMutableString string];
NSMutableArray *updateValues = [NSMutableArray array];
for (int i = 0; i < selfcolumeNamescount; i++) {
NSString *proname = [selfcolumeNames objectAtIndex:i];
if ([proname isEqualToString:primaryId]) {
continue;
}
[keyString appendFormat:@" %@=?,", proname];
id value = [self valueForKey:proname];
if (!value) {
value = @"";
}
[updateValues addObject:value];
}

//删除最后那个逗号
[keyString deleteCharactersInRange:NSMakeRange(keyStringlength - 1, 1)];
NSString *sql = [NSString stringWithFormat:@"UPDATE %@ SET %@ WHERE %@ = ?;", tableName, keyString, primaryId];
[updateValues addObject:primaryValue];
res = [db executeUpdate:sql withArgumentsInArray:updateValues];
NSLog(res?@"更新成功":@"更新失败");


}];
return res;
}

打印更新成功，但是表中的数据没有变化，求解，在线急，你QQ是多少

**Comment by j364960953** [comment]
解决了，更新模型的时候需要设置一下pk.问一下，saveorUpdate,这个方法什么时候我需要主动设置模型的pk吗？

**Comment by Joker-King** [comment]
这个方法其实内部是通过主键PK来判断，如果主键存在，则执行update，如果主键不存在，则执行save。所以要看你的数据pk是否有值~
