### ISSUE TITLE
删除表操作

### ISSUE THREAD

**Issue by ZYTSingleNoble** [Haley-Wong/JKDBModel#14]
没有发现删除表操作，而且删除表的话，也打算用model去操作么？设计的字段更新蛮不错的，也不用考虑属性变了，数据库升级之类的。

**Comment by Halley-Wong** [comment]
删除表的需求略奇怪，对象类存在的话，表就存在；如果是针对app升级，数据迁移的话，需要自己处理的地方比较多，所以建议删除表也放在一起
