### ISSUE TITLE
请问使用JKDBModel出现如下问题

### ISSUE THREAD

**Issue by 542604974** [Haley-Wong/JKDBModel#17]
请问使用JKDBModel出现如下问题，我的每一个关键字都有值的
DB Query: INSERT INTO ZQFocusData(friends_id,friends_user_guid,nickname,logo,friends_status,friends_sex,friends_city,city,city_name,is_hufen,user_guid,isAddActivity,name,ios_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?);
2016-03-10 17:41:14.287 SporterMan[47210:347830] Unknown error calling sqlite3_step (8: attempt to write a readonly database) eu

**Comment by 542604974** [comment]
if ([data[0] count] > 0) { // 有数据才添加
        for (int i=0; i<data.count; i++) {
            self.focusData = [[ZQFocusData alloc] init];
            self.focusData = [ZQFocusData objectWithKeyValues:data[i]];
    
            //保存到数据库
            dispatch_async(dispatch_get_global_queue(0, 0), ^{
                     [self.focusData save];
            });

            }
        }
    });

我的代码是这样的

**Comment by Halley-Wong** [comment]
你的数据库是只读权限，不能写入，你尝试一下把应用删掉，重新跑一次试试

**Comment by Halley-Wong** [comment]
如果还有问题，把demo发给我

**Comment by 542604974** [comment]
我重新开一个项目使用又正常了，而我的另外一个项目APP第一次打开是上面那样情况，然后重新打开又可以正常插库了，demo都是按照你的方法做的，给model赋值就save了，而且我使用中发现另外一个问题，如果同时插入两个表数据，然后APP就奔溃了，奔在save这个方法里面。

**Comment by Halley-Wong** [comment]
同时插入两个表是怎么操作的，开两个线程同时插入不同的表？

**Comment by 542604974** [comment]
是啊,因为我首页类似于新闻那样，会展现多个页面，但我现在更改了scrollView，好像又没事了。

**Comment by Halley-Wong** [comment]
刚才这样测试，也没问题啊
for (int i = 0; i < 10; i++) {
        User *user = [[User alloc] init];
        user.name = [NSString stringWithFormat:@"麻子%d",i];
        user.sex = @"男";
        user.age = 10+i;
        dispatch_async(dispatch_get_global_queue(0, 0), ^{
            [user save];
        });
        dispatch_async(dispatch_get_global_queue(0, 0), ^{
            Depart *depart = [[Depart alloc] init];
            depart.departName = [NSString stringWithFormat:@"部门%d",i];
            depart.departNum = [NSString stringWithFormat:@"%d",1000 + i];
            [depart save];
        });
    }

**Comment by 542604974** [comment]
是放到不同线程里的问题吗？

**Comment by Halley-Wong** [comment]
上面正常，证明不是
