### ISSUE TITLE
使用指定路径方式创建数据库后，插入数据莫名插入默认的数据库中

### ISSUE THREAD

**Issue by ShaochongDu** [Haley-Wong/JKDBModel#20]
在使用[[LKDBHelper alloc]initWithDBPath:self.dbpath]或LKDBHelper *dbHelper = [LKDBHelper getUsingLKDBHelper];  [dbHelper setDBName:@"test.db"];自定义方式创建数据库时，插入数据老是会到默认的数据库LKDB中，不知道为什么？

**Comment by Haley-Wong** [comment]
你这个问题提到作者的工程issues里啊！你可以测试修改他demo工程的路径，如果没问题的话，可能是你使用错误了。
