### ISSUE TITLE
请问JKDBModel能够通过CocosPods安装么？

### ISSUE THREAD

**Issue by CoderTaoX** [Haley-Wong/JKDBModel#23]

**Comment by Haley-Wong** [comment]
@CoderTaoX 不支持，原因有二：1、这个库对FMDB的依赖太强。2、库的文件较少也就两个类而已。

**Comment by BillZong** [comment]
有理, Pods安装如果对其它库依赖太大, 还是不建议提供的. 

可以考虑把数据库层抽离个Protocol, 基础实现是sqlite3; 用户可根据需要继承并实现数据库实现部分, 达到跟具体数据库的实现分离. 这样估计就可以考虑使用Pods了?

**Comment by Haley-Wong** [comment]
@BillZong 思路不错。
