### ISSUE TITLE
存放NSdata是不行的？如果要改的话应该怎么去修改比较合理呢，麻烦大神帮帮忙看看

### ISSUE THREAD

**Issue by MYliuxiang** [Haley-Wong/JKDBModel#25]

**Comment by Haley-Wong** [comment]
建议NSData 就不要存数据库了吧，存到本地目录中，然后把文件地址存进数据库。
如果非要存NSData，那就得在类型判断里针对NSData 做处理了，然后从数据库取数据的时候也处理。需要自己在扩展这个库了。

**Comment by aichenchen** [comment]
这个我没有太明白，这个NSData应该怎么处理呢？这个封装的暂时不支持吗？

**Comment by Haley-Wong** [comment]
不支持，数据传输一般都是基本数据类型，加上一些基本数据类型的封装对象类，如NSNumber 等。对于NSData ，我建议是保存在本地沙盒内，然后数据库存一个该文件的地址。
思路跟下载图片保存在本地沙盒内，然后数据库里只是存图片在本地的地址是一样的。
