### ISSUE TITLE
楼上两位是开着大小号在喷人给自己打广告的吧

### ISSUE THREAD

**Issue by Haley-Wong** [Haley-Wong/JKDBModel#3]
本人只是自己总结了下在项目中用到的东西，封装思路来自：https://github.com/li6185377/LKDaoBase，跟你们没一毛钱关系

**Comment by heyehao2008** [comment]
支持楼主，那个nsdictionary就一装逼犯，写的东西不咋地就爱瞎咋呼，出个低级的框架就吼着秒杀这个秒杀那个，看着就烦。曾经怀着探讨技术的目的加入他建的群，结果群里全是一群装逼犯，啥技术不懂一天还就爱吹嘘自己的工资多高。从此就反感这个人了。也看了下他一个框架的源码，说实话，技术也就能忽悠下刚入行的，不知道建那么多群笼络那么多的菜鸟想干嘛，估计是想经营粉丝，还比较有经济头脑，哈哈哈
