### ISSUE TITLE
怎么取用NSData？

### ISSUE THREAD

**Issue by aichenchen** [Haley-Wong/JKDBModel#30]
已有数据库，怎么取用NSData？应该怎么修改，可以取用NSdata？

**Comment by aichenchen** [comment]
这个框架很好用，但是一旦用到Blob就麻烦了，更搞笑的是我还不会改，觉得更坑死了

**Comment by Haley-Wong** [comment]
Blob 是数据库字段的类型，但是实际上Sqlite 数据库是不对数据类型验证的（例如，数据表表中某个字段设置为Integer类型，然是依然可以插入一个字符串进去，而且不会报错）。正如我在另一个issues 里回答的一样，我建议你把这个文件保存到本地，然后生成一个地址，保存到数据库中。因为Blob 类型一般都是放文件的二进制数据，例如图片，放多了会导致数据库变大，数据操作变慢，而且也不容易查看文件数据。 @aichenchen

**Comment by aichenchen** [comment]
谢谢～～，我这里是已有数据库，我不用往里面存储，只需要读取，这个框架读不出来，直接用fmdb可以读取，如果没发取用，我再想想办法综合一下。这个框架真的很好用～～如果再完美点就更好了｀｀

**Comment by Haley-Wong** [comment]
如果你想改，只需要 JKDBModel 类里的 -getPropertys 方法中加上NSData 类型的判断，然后在findByCriteria 和findAll 方法里，也有一个类型判断，用对应的类型处理就好。如果这两天有时间，我就改一下，再提交。到时候@ 你。

**Comment by 0xhellohaley** [comment]
@aichenchen 已经添加了NSData 类型数据的读写功能。给你看下我修改了哪些地方：
![1234567890](https://cloud.githubusercontent.com/assets/7069859/18942441/a90adddc-864b-11e6-9de6-1b6d80dedc63.png)

**Comment by aichenchen** [comment]
谢谢，谢谢，谢谢！大神真棒。
